USE CLARITY

-- TESTING vwCLARITY_SER_OT_PROV_TYPE
SELECT PAT_ENC_CSN_ID, vsa.CONTACT_DATE, vsa.PROV_ID, vsa.PROV_NAME_WID, ptot.PROV_TYPE_OT_NAME, pt.NAME AS PROV_TYPE_CURR_NAME
FROM V_SCHED_APPT vsa
	LEFT JOIN CLARITY_SER									ser		ON	vsa.PROV_ID = ser.PROV_ID
	LEFT JOIN ZC_PROV_TYPE									pt		ON	ser.PROVIDER_TYPE_C = pt.PROV_TYPE_C
	LEFT JOIN Clarity_App.Rptg.vwCLARITY_SER_OT_PROV_TYPE	ptot	ON	vsa.PROV_ID = ptot.PROV_ID 
																AND		vsa.CONTACT_DATE BETWEEN ptot.CONTACT_DATE AND ptot.EFF_TO_DATE
WHERE vsa.PROV_ID = '98059'
ORDER BY CONTACT_DATE

SELECT ot.PROV_ID, ot.CNCT_NUM, ot.CONTACT_DATE_REAL, ot.CONTACT_DATE, ot.PROV_TYPE_OT_C, ser.PROVIDER_TYPE_C
FROM CLARITY_SER_OT ot
	LEFT JOIN CLARITY_SER	ser	 ON ot.PROV_ID = ser.PROV_ID
WHERE ot.PROV_ID = '98059'
