USE [DS_HSDW_App_Dev]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF EXISTS (SELECT 1 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_SCHEMA='CallCenter'
    AND TABLE_TYPE='BASE TABLE' 
    AND TABLE_NAME='ACC_Workgroup_Pod_Mapping')
   DROP TABLE CallCenter.ACC_Workgroup_Pod_Mapping
GO

CREATE TABLE [CallCenter].[ACC_Workgroup_Pod_Mapping](
	[sk_ACC_Workgroup_Pod_Mapping] [INT] IDENTITY(1,1) NOT NULL,
	[Workgroup] [VARCHAR](150) NULL,
	[Pod] [VARCHAR](100) NULL,
	[OperationalOwner] [VARCHAR](254) NULL,
	[Load_Dte] DATETIME NOT NULL,
	[ETL_guid] [VARCHAR](38) NOT NULL,
 CONSTRAINT [pk_ACC_Workgroup_Pod_Mapping] PRIMARY KEY CLUSTERED 
(
	[sk_ACC_Workgroup_Pod_Mapping] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


