USE DS_HSDM_App_Dev

SELECT PAT_ENC_CSN_ID
     , PROV_ID
	 , CONTACT_DATE
	 , PROV_TYPE_OT_NAME
FROM Stage.Scheduled_Appointment
ORDER BY PROV_TYPE_OT_NAME
       , PROV_ID
	   , CONTACT_DATE

MERGE  Stage.Scheduled_Appointment tgt
USING Rptg.vwCLARITY_SER_OT_PROV_TYPE src
ON tgt.PROV_ID = src.PROV_ID AND tgt.CONTACT_DATE BETWEEN src.CONTACT_DATE AND src.EFF_TO_DATE
WHEN MATCHED THEN UPDATE SET tgt.PROV_TYPE_OT_NAME = src.PROV_TYPE_OT_NAME;